gettext_0.19.4.bbappend: support for mingw
This patch solves various unresolved references:

 .libs/fstrcmp.o:fstrcmp.c:(.text+0x4b6): undefined reference to `_imp__pthread_key_create'
 .libs/fstrcmp.o:fstrcmp.c:(.text+0x5b2): undefined reference to `_imp__pthread_once'
 .libs/fstrcmp.o:fstrcmp.c:(.text+0x5c4): undefined reference to `_imp__pthread_getspecific'
 .libs/fstrcmp.o:fstrcmp.c:(.text+0x617): undefined reference to `_imp__pthread_setspecific'
 .libs/localename.o:localename.c:(.text+0x14f6): undefined reference to `_imp__pthread_mutex_lock'
 .libs/localename.o:localename.c:(.text+0x1576): undefined reference to `_imp__pthread_mutex_unlock'
 .libs/localename.o:localename.c:(.text+0x15c9): undefined reference to `_imp__pthread_mutex_unlock'
 glthread/.libs/lock.o:lock.c:(.text+0xe): undefined reference to `_imp__pthread_mutexattr_init'
 glthread/.libs/lock.o:lock.c:(.text+0x2d): undefined reference to `_imp__pthread_mutexattr_settype'
 glthread/.libs/lock.o:lock.c:(.text+0x44): undefined reference to `_imp__pthread_mutex_init'
 glthread/.libs/lock.o:lock.c:(.text+0x53): undefined reference to `_imp__pthread_mutexattr_destroy'
 glthread/.libs/lock.o:lock.c:(.text+0x62): undefined reference to `_imp__pthread_mutexattr_destroy'
 glthread/.libs/lock.o:lock.c:(.text+0x75): undefined reference to `_imp__pthread_mutexattr_dest

Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 8eadfbd7e07b498b58fd2730af79f1ace07afcc8)